### ISSUE TITLE
Delete trailing spaces command respects trailing_spaces_modified_lines_only

### ISSUE THREAD

**Issue by george-norris-salesforce** [SublimeText/TrailingSpaces#101]
`Edit > Trailing Spaces > Delete`  
..does not delete anything in ST3

**Comment by jbrooksuk** [comment]
Works here :)

- What version of ST3 are you using?
- What OS are you on?

**Comment by george-norris-salesforce** [comment]
Sublime Text Build 3103
OS X 10.11.3

**Comment by overkill22** [comment]
Same problem here on Mint 17.3 and 3114
I see the lines highlighted but when I try to `Edit > Trailing Spaces > Delete` nothing happen.
I can see at the bottom the status bar that said `Deleted 14 trailing spaces regions`.

**Comment by ericdlaspe** [comment]
I have the same problem.  I try `Trailing Spaces: Delete Trailing Spaces`, and none are deleted.
The status bar says, "No trailing spaces to delete!" though many are highlighted.

ST3:  3126
macOS:  10.12

**Comment by ericdlaspe** [comment]
As a workaround, you can use Cmd/Ctrl-F (enable Regular Expressions), `[ ]+(?=\n)`, Find All, Delete/Backspace

**Comment by ericdlaspe** [comment]
This may not be a bug per se.  `Edit > Trailing Spaces > Delete` and `Cmd/Ctrl-Shift-P Trailing Spaces: Delete Trailing Spaces` seem to (unfortunately) respect this setting: `"trailing_spaces_modified_lines_only": true`

That means even when you explicitly invoke the plugin--perhaps out of a desire to clean up an existing file--lines you haven't edited will be ignored.

**Comment by rchl** [comment]
This is working per design and it's documented in https://github.com/SublimeText/TrailingSpaces/blob/master/README.md#modified-lines-only
