### ISSUE TITLE
Option to only show trailing spaces on actual files

### ISSUE THREAD

**Issue by HughMacdonald** [SublimeText/TrailingSpaces#102]
Hi,

I use GitSavvy with Sublime Text 3, along with Trailing Spaces, which I really appreciate.

What I'm finding, though, is that GitSavvy will often show me a page, for example a diff, and there will be some lines that have a single space, and nothing else. TrailingSpaces is flagging these lines, as I would expect.

Can I suggest an option to not show tailing spaces on scratch files, as I'm finding that the best way to differentiate seems to be with `window.active_sheet().view().is_scratch()`?

Thanks

**Comment by rchl** [comment]
Scratch views are currently ignored.
