### ISSUE TITLE
Deleting Empty Lines Question

### ISSUE THREAD

**Issue by manning390** [SublimeText/TrailingSpaces#103]
I have the trailing_spaces_include_empty_lines set to true (as default)

I am not sure if it is broken or if I am interpreting its function wrong.

If I have the following code:

```
var x = 5;



if(x == 5){
 // Do something

}

```

Will it just delete any spaces on empty lines or will it delete all but one line between the variable declaration and the if statement?

I was under the impression it would delete groups of blank lines leaving only 1.

**Comment by rchl** [comment]
This plugin doesn't delete empty lines, just trailing spaces on empty lines.
