### ISSUE TITLE
Plugin makes Sublime Text significantly slower

### ISSUE THREAD

**Issue by compie** [SublimeText/TrailingSpaces#107]
After installing this package scrolling through a large text file becomes a lot slower. The UI is not updated very often anymore. Disabling the plugin immediately fixes the problem.

**Comment by aramk** [comment]
I'm experiencing very slow typing in the find box. For some reason it's running the plugin on the whole file each time I type a character...

**Comment by jbrooksuk** [comment]
What version of ST are you both using?

**Comment by compie** [comment]
I'm using ST build 3114

2016-08-08 15:31 GMT+02:00 James Brooks <notifications@github.com>:

**Comment by aramk** [comment]
3114 for me also

**Comment by compie** [comment]
Is there any plan to solve this? Otherwise I might look into it myself.

**Comment by rchl** [comment]
A lot has changed since this issue was created but the latest version has many performance improvements (processing only visible region, running handler in a separate thread) so it will never cause issues with typing.
