### ISSUE TITLE
Error trying to parse settings: Invalid Escape

### ISSUE THREAD

**Issue by sanchezelton** [SublimeText/TrailingSpaces#108]
Tried using this as usersettings in ST3 Build 3114, running on Windows 7, to pick up all whitespace characters (including space, tab, line feed, form feed etc.) + control characters:
`
"trailing_spaces_regexp": "[\c[A-Z]\s]+"`

Also tried being satisfied with just all whitespace characters:

`"trailing_spaces_regexp": "[\s]+"`

However, neither of these work and ST3 reports the error given in the subject.

These are valid JS RegExp [character classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#character-classes) and ought to work.

**Comment by rchl** [comment]
Since you are inside string in a JSON document, you need to escape twice - `"\\s"`.
