### ISSUE TITLE
TrailingSpaces has trailing spaces in README on Package Control

### ISSUE THREAD

**Issue by roehst** [SublimeText/TrailingSpaces#112]
An image is worth a thousand words.

![image](https://cloud.githubusercontent.com/assets/21047691/23224500/76ad5b0a-f90d-11e6-9c0c-f048f450aca5.png)

**Comment by jbrooksuk** [comment]
Oddly, the messages themselves do not..

**Comment by roehst** [comment]
Yep, it is funny
