### ISSUE TITLE
Trailing spaces not highlighted in second column

### ISSUE THREAD

**Issue by adis-io** [SublimeText/TrailingSpaces#114]
### Expected behaviour
Trailing spaces should be highlighted in second (third and other) columns

### Actual behaviour
Trailing spaces not highlighted in second (third and other) columns

### Steps to reproduce
1) Change to two column view - View -> Layout -> Columns: 2
2) Open file in second column
3) Try to write whitespaces

**Comment by rchl** [comment]
WFM ST4070
