### ISSUE TITLE
Does not highlight anything in Sublime 3, even after setting trailing_spaces_highlight_color

### ISSUE THREAD

**Issue by aminariana** [SublimeText/TrailingSpaces#116]
Repro:
1. Install via package installer on Sublime 3 with MacOS Classic theme
2. Set `trailing_spaces_highlight_color` to one of `invalid`, `error` or `comment`

Expected:
Highlighted trailing spaces

Actual:
Not highlighted ever, with or without the setting. (Delete does work)

**Comment by stav** [comment]
I had this problem all of a sudden, can't remember when it started, but I basically just had to enter a value and restart. See : https://stackoverflow.com/questions/16916060#answer-23051790

**Comment by webdevnerdstuff** [comment]
I'm also having this problem with Build 3148. Nothing changes the color, including adding custom color scope.

**Comment by Pictor13** [comment]
Because of how the code is written you need to save the setting file and close Sublime, before it works.

**Comment by rchl** [comment]
Duplicate of #65
