### ISSUE TITLE
trim on save/save on trim not working

### ISSUE THREAD

**Issue by opichon** [SublimeText/TrailingSpaces#119]
I've set these settings:
``` 	
"trailing_spaces_save_after_trim": true,
"trailing_spaces_trim_on_save": true,
```
Neither works.

**Comment by butsjoh** [comment]
i have the same issue on sublime 3

**Comment by andrewtcrooks** [comment]
I'm also having this problem.

**Comment by mbarwick83** [comment]
Any update?

**Comment by claudiosegala** [comment]
Same here

**Comment by bsienn** [comment]
Same

Fedora 29
Sublime text 3 (3.1.1 - 3176)

**Comment by anjathiart** [comment]
same here sublime 3

**Comment by rchl** [comment]
> I don't really want to install the `TrailingSpaces` plugin if I can just add it to settings.

Do you have the `TrailingSpaces` package installed or not? Those settings only work when this package is installed.

**Comment by rchl** [comment]
Closing as this is either fixed or was a user error.

If this still doesn't work for someone then feel free to provide repro steps.

**Comment by yegor256** [comment]
@rchl I have `TrailingSpaces` installed, but the feature doesn't work -- trailing spaces are not removed, neither automatically not manually through the menu command

**Comment by rchl** [comment]
Create a new issue and provide details about your settings, the file you are trying on etc.
