### ISSUE TITLE
Should be disabled on console.

### ISSUE THREAD

**Issue by bantya** [SublimeText/TrailingSpaces#120]
This plugin is great and works like charm for everyone using it.
The only downside I think is it also highlights trailing spaces in console also. I have to do a lot of console work natively in sublime. Most of the times the highlighted trailing spaces is what divert focus from console output to the highlight color.

![image](https://user-images.githubusercontent.com/16685565/29493063-0389798e-85ac-11e7-85b6-ffec1c731a58.png)

There should be an option in settings file to disable it for console like `"disable_for_console" : true,`. Where it should work fine for code edits and be disabled for console like:

![image](https://user-images.githubusercontent.com/16685565/29493081-712b6092-85ac-11e7-97a6-731837b9f4ca.png)

**Comment by Kamik423** [comment]
There should in general be an option to disable it in the panel. It also plays really badly with Terminus.

<img width="1057" alt="Screen Shot 2019-12-05 at 13 33 21" src="https://user-images.githubusercontent.com/16278233/70235760-d4f13480-1763-11ea-95ff-35d79e4ad686.png">
