### ISSUE TITLE
This plug-in causes the Terminus plug-in command line background to have a lot of white

### ISSUE THREAD

**Issue by Brolly0204** [SublimeText/TrailingSpaces#127]
![1581151123508](https://user-images.githubusercontent.com/16096724/74082102-8fb5ef80-4a91-11ea-893b-b44214d40aa9.jpg)

**Comment by zishang520** [comment]
"trailing_spaces_syntax_ignore": ["Plain text"]

**Comment by rchl** [comment]
Duplicate of #120
