### ISSUE TITLE
Trailing Spaces are failed to start

### ISSUE THREAD

**Issue by don-pit** [SublimeText/TrailingSpaces#135]
Sublime Text 2 is failed to start with message "Error trying to parse file: Trailing comma before closing backet in C:\Users\<...>\AppData\Roaming\Sublime Text 2\Packages\TrailingSpaces\Main.sublime-menu:49:33". The ST window doesn't appear. The process remains alive and prevents another instances from start.

It seems that revision cb6639a395d8e3d24c5ebfecc689798f79477909 introduces some violations of JSON format to the `Main.sublime-menu`.

Sublime Text 2.0.2 buld 2221
Trailing Spaces v.1.0.0

**Comment by rchl** [comment]
What's the reason you are still on v2?
The last release was in 2013. That's an eternity for a software.
The current plan is to remove support for ST2 really.

**Comment by don-pit** [comment]
It just works fine. (And a license:))

**Comment by rchl** [comment]
I'll try to fix that by releasing the last working ST2-compatible version for ST2 only.

It won't get any more updates though while the latest (ST3-compatible) version is receiving major performance improvements.

**Comment by rchl** [comment]
ST2 should now be getting compatible version through package control (one tagged with `st2-` prefix in the repo).
