### ISSUE TITLE
Affect only selected lines if selection exists

### ISSUE THREAD

**Issue by elmimmo** [SublimeText/TrailingSpaces#14]
If I have a selection of 1 line or more, I would expect the command to only affect it. It affects the whole document.

Sometimes I use Markdown-like comments inside code (see https://github.com/rtomayko/rocco or https://github.com/rtomayko/shocco). Markdown expects two blank white spaces at the end to signal a line break. I would like, then. to be selective on where trailing spaces are to be removed: yes in code, no in comments.

**Comment by rchl** [comment]
This is possible to do now by customizing `trailing_spaces_scope_ignore`.
