### ISSUE TITLE
view_syntax issue

### ISSUE THREAD

**Issue by eblot** [SublimeText/TrailingSpaces#142]
I've been unable to use the trailing spaces highlighting for a while, despite the Delete Trailing space menu always work.

I noticed from the console the following error in trailing_spaces.py@185:

    NameError: global name 'view_syntax' is not defined

and indeed, `view_syntax` does not seem defined

is `view_syntax` could be something like

    view_syntax = view_settings.get('syntax')

?

**Comment by rchl** [comment]
Wow, indeed.

**Comment by rchl** [comment]
BTW. You are getting this error because you have customized `syntax_ignore`  setting. That one is deprecated (but will still work) by new, preferred `scope_ignore` setting.

**Comment by rchl** [comment]
Fix released in v1.3.3.

**Comment by eblot** [comment]
> BTW. You are getting this error because you have customized `syntax_ignore` setting. That one is deprecated (but will still work) by new, preferred `scope_ignore` setting.

I think it comes from quite an old setting. Before digging into the code, I uninstalled/reinstalled TrailingSpaces, but the old settings have been preserved, and I did not know which one were up to date. I'll update them, thanks for the hint.

**Comment by rchl** [comment]
Open TrailingSpaces settings from the command palette. Your customized settings should be on the right.
