### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by SamuelBenard** [SublimeText/TrailingSpaces#147]
I installed TrailingSpaces v1.3.3 on sublimetext 3.2.2 3211on Linux Mint
and noticed a high CPU usage on my core I7. The process plugin_host is between 10% and 20% with peaks between 25% and 30%

I uninstalled TrailingSpaces, everything back to normal. I uninstalled all packages and reinstalled TrailingSpaces. High CPU again.
Some files I edit are 5000 lines perl code and i'm connected through sshfs to the server.

I can do more tests if needed

**Comment by rchl** [comment]
Duplicate of #144
