### ISSUE TITLE
Doesn't work on Sublime Text 4

### ISSUE THREAD

**Issue by adithyag** [SublimeText/TrailingSpaces#150]
I installed TrailingSpace v1.3.4 installed on Sublime Text 3 on Ubuntu 20.04 LTS. I recently upgraded to Sublime Text 4. TrailingSpaces package no longer shows red highlights for trailing white space. I have default settings.

**Comment by rchl** [comment]
It works here.
You need to provide more information.
- Does it work if you open a blank file and add spaces?
- Have you customized any TrailingSpaces settings?
- Do you see any errors in the ST console since start of ST?

**Comment by adithyag** [comment]
It happened after I upgraded the license. After I restarted Sublime Text and toggled trailing spaces, it works again. Feel free to close this.

**Comment by rchl** [comment]
Some packages break on updating. Especially if it's an update from ST3 to ST4 version. So restarting ST never hurts and is an expected solution for such problems.
