### ISSUE TITLE
Handle empty settings file

### ISSUE THREAD

**Issue by chikamichi** [SublimeText/TrailingSpaces#35]
ST2 dislikes empty settings files. It requires extra-care and currently the code is filled with redundant default values (as constants) to ensure the settings globals are in proper order during execution… ST3 will ignore empty files at `load_settings` time to handle this.

As for ST2 is concerned, maybe this could be improved by checking whether the settings file is empty and, if so, getting rid of it before late.

**Comment by rchl** [comment]
ST2 issue so not worth addressing.
