### ISSUE TITLE
Option to disable trimming trailing whitespace on lines with only whitespace

### ISSUE THREAD

**Issue by Tyilo** [SublimeText/TrailingSpaces#44]
For example, I would an option to make `TralingSpaces` work like this:

```
def foo():
    print("a")
    # Don't delete whitespace on the following line:

    print("b")
```

So replace `([^\s])\s*$` with `\1`.

**Comment by redbassett** [comment]
:+1:

I would like to trim trailing whitespace on lines with code, but not on lines with indentation but no code.

**Comment by rchl** [comment]
I think it's out of scope of this package.
To me it really doesn't make sense to leave some trailing spaces.
