### ISSUE TITLE
Weird interaction with highlighting?

### ISSUE THREAD

**Issue by frasmage** [SublimeText/TrailingSpaces#50]
This package occasionally seem to break the behaviour of the text selection feature of ST2 (i.e. click and drag over text).

Occasionally, when attempting to select text, the beginning of the selection always jumps to the very bottom of the document and updates very jaggedly. 

This usually seems to occur when the bottom line of the document is in view. Scrolling up and back down seems to temporarily fix the issue, though it eventually reoccurs. Deactivating this package seems to have removed the issue.

In case the issue is a conflict with other packages, I also have the following installed:
- SublimeLinter
- Emmet
- Git
- Package Control
- NodeJS

**Comment by rchl** [comment]
I have never seen that happen.
Please let me know if you still see this problem in ST3+ and ideally provide reliable reproduction steps.
