### ISSUE TITLE
Package Control: The package specified, TrailingSpaces, is not available.

### ISSUE THREAD

**Issue by rr1000** [SublimeText/TrailingSpaces#56]
Just started getting this a few days ago. Attempted to reinstall but searching TrailingSpaces in package control doesn't even return a plugin now.

**Comment by rchl** [comment]
Might be broken in ST2 (haven't checked as ST2 doesn't even run on latest OSX) but it's on PackageControl - https://packagecontrol.io/packages/TrailingSpaces
