### ISSUE TITLE
TrailingSpaces package does not work in ST2

### ISSUE THREAD

**Issue by cybd** [SublimeText/TrailingSpaces#59]
I have ST2. Option "auto_upgrade" set to "true" in my Package Control settings. Today I've noticed that TrailingSpaces package does not work properly: neither highlight, nor remove trailing spaces.
I tried to remove/install package -- no changes.

Sublime Text v. 2.0.2
TrailingSpaces v.2013.07.25.08.58.10;github.com/SublimeText/TrailingSpaces

But in ST3 this package works fine.

**Comment by rchl** [comment]
I'd consider ST2 unsupported now.
