### ISSUE TITLE
Wrong lines being highlighted

### ISSUE THREAD

**Issue by shacker** [SublimeText/TrailingSpaces#66]
Either I'm misunderstanding how this works or it's doing something odd with Python. In this screenshot, there is NO trailing space on the first line, but it's being highlighted. There ARE trailing spaces on the second line, but it's not being highlighted. 

Can you clarify please? Thanks.

![screen shot 2013-12-04 at 2 18 17 pm](https://f.cloud.github.com/assets/102694/1678077/3e289b2a-5d32-11e3-8b67-eae74895c229.png)

**Comment by rchl** [comment]
This doesn't look like highlighting created by this plugin (it would be red).
