### ISSUE TITLE
Doesn't seem to work with ST2

### ISSUE THREAD

**Issue by felixalias** [SublimeText/TrailingSpaces#77]
Hey, installed via Package Control and I don't see any highlighting showing up (nor does the delete trailing spaces command do anything - "no trailing spaces found").

**Comment by Honghe** [comment]
not work on st2 too.

**Comment by iamntz** [comment]
Why not update to ST3? It's just a matter of time for plugin developers to ditch ST2...

**Comment by jbrooksuk** [comment]
I believe we've dropped support for ST2? Can anyone confirm @SublimeText/developers

**Comment by FichteFoll** [comment]
```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 200, in on_selection_modified
    callback.__module__, "on_selection_modified", FAST_EVENT_TIMEOUT)
  File ".\sublime_plugin.py", line 154, in run_timed_function
    ret = f()
  File ".\sublime_plugin.py", line 199, in <lambda>
    run_timed_function(lambda: callback.on_selection_modified(v),
  File ".\trailing_spaces.py", line 416, in on_selection_modified
  File ".\trailing_spaces.py", line 129, in match_trailing_spaces
  File ".\trailing_spaces.py", line 92, in find_trailing_spaces
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Also, I'm sorry, but I made the package control messages view read only in wbond/package_control#893 so you won't be able to remove them as a kind of "introductory task". It's not yet merged though.

**Comment by shellscape** [comment]
anyone know what the last working version for ST2 is?

**Comment by rchl** [comment]
I'd consider ST2 no longer supported.

**Comment by shellscape** [comment]
Wow. Three years. Zombie issue!
