### ISSUE TITLE
TrailingSpaces always trims on save although it's set to false

### ISSUE THREAD

**Issue by Heart1010** [SublimeText/TrailingSpaces#79]
I'm on Linux build ST3 3065 and although I kept the default settings

``` JSON
{
    "trailing_spaces_modified_lines_only": false,
    "trailing_spaces_trim_on_save": false,
}
```

the plugin **always** deletes all whitespaces in my file **when I save it**.

**Comment by YurkoHoshko** [comment]
@BenMQ I have not any other tools that could conflict with TrailingSpaces and I have the same issue as @Heart1010 .

**Comment by arkhi** [comment]
I’m on MacOSX with a build 3103.

After removing the folders “Installed Packages” and “Packages” in /Users/fabien//Library/Application Support/, I have the same issue: The lines are trimmed by default, even though the default SublimeText default settings (“/Users/fabien/Library/Application Support/Sublime Text 3/Packages/Default/Preferences.sublime-settings”) for `trim_trailing_white_space_on_save` is set to `false`.

Is there a way to check what is the actual value for a specific setting?

**Comment by lakesare** [comment]
Thank you @BenMQ, I had `trim_trailing_whitespace` set to true in `.editorconfig`.

**Comment by rchl** [comment]
Resolving as I've tested this and it appears to work for me now (few years later). If it doesn't for someone then we need more info.
