### ISSUE TITLE
Stopped working after update to ST3 build 3065

### ISSUE THREAD

**Issue by kitsguru** [SublimeText/TrailingSpaces#81]
Windows 7 64 bit 
ST3 build 3065

Deleted package, restarted ST and re-installed. Still not working and empty line under edit menu where TS normally exists.

**Comment by razmo** [comment]
I have the same issu on linux mint !

**Comment by razmo** [comment]
This one do the same think and work fine : https://packagecontrol.io/packages/Trimmer

**Comment by zyphlar** [comment]
Build 3065 on Linux (Ubuntu 64-bit) not working for me either. The menu items seem to show up but no highlighting. The HighlightWhitespaces plugin works for me however.

**Comment by jbrooksuk** [comment]
I'm on build 3070 (OSX 10.10) and it's working fine.

**Comment by Sinetheta** [comment]
Unfortunately @zyphlar that plugin highlight *all* whitespace, which is pretty terrible.

**Comment by kitsguru** [comment]
It is now working fine for me, only highlighting trailing spaces.

**Comment by zyphlar** [comment]
@Sinetheta I have an open pull request for HighlightWhitespaces to add end-of-line whitespace as an option: https://github.com/disq/HighlightWhitespaces/pull/14/files

Then you can disable the other whitespace detection with highlight_whitespaces.sublime-settings: 

```
{
  "highlight_whitespaces_check_spaces": false,
  "highlight_whitespaces_check_tabs": false,
  "highlight_whitespaces_check_eol": true,
}
```
