### ISSUE TITLE
Highlights trailing spaces in input fields

### ISSUE THREAD

**Issue by kugland** [SublimeText/TrailingSpaces#84]
I’m using Sublime Text 3 on Linux, and I found this strange behaviour in this plugin: it highlights trailing space in the search/replace input fields, as can be seen in the image below.

![trailing](https://cloud.githubusercontent.com/assets/1173932/7311838/2ffb6ed2-ea18-11e4-88bb-f0a09c51b979.png)

**Comment by rchl** [comment]
With trailing_spaces_include_current_line = false at least you won't see this problem in single-line inputs. A bit of a workaround I guess.

**Comment by rchl** [comment]
Although there is a way to fix it by checking view.settings().get('is_widget').
