### ISSUE TITLE
trailing_spaces_highlight_color not working

### ISSUE THREAD

**Issue by heitorsilva** [SublimeText/TrailingSpaces#87]
Hello!

I'm using Sublime Text 3 (3083), and a IR_Black theme. My user settings for TrailingSpaces are as follows:

``` plaintext
{
   "trailing_spaces_highlight_color": "",
   "trailing_spaces_regexp": "(?<=\\S)[\t ]{2,}|[ \t]{2,}$|(!?^\\s+)"
}
```

The result I get is always this white background with red borders, no matter what I put inside hightlight_color setting.

![image](https://cloud.githubusercontent.com/assets/878699/8238161/51262038-15ca-11e5-9d0f-0187057c7d68.png)

All the other settings work fine if I insert them on my user config, just highlight that doesn't. Already tried suggestions from #4 and #12, but none worked.

What should I do? This white thing bothers me...

**Comment by heitorsilva** [comment]
I've found out that it only works when I close Sublime and re-open it. Is that the expected behaviour? Shouldn't it auto-reload when the settings file is saved?

**Comment by rchl** [comment]
Currently, settings are only read on load. It could be fixed but that's not part of this issue.
