### ISSUE TITLE
"file_max_size" not taken into account?

### ISSUE THREAD

**Issue by VipSaran** [SublimeText/TrailingSpaces#89]
In ST2 (64bit on Win 7), the default for `trailing_spaces_file_max_size` is 1048576, but when opening 50MB file, I get this error:

![trailing](https://cloud.githubusercontent.com/assets/995948/8396463/b2f54850-1da6-11e5-8563-9b45ee569522.png)

Expected behavior would be that plugin first checks for file size and, if it exceeds the supported max, it "shuts itself off" (effectively doing `trailing_spaces_enabled=false`).

**Comment by fritz-c** [comment]
Did you register the setting in your generic `Preferences.sublime_settings` file, or the package-specific `trailing_spaces.sublime_settings` file? I think the setting needs to be in the latter.

**Comment by rchl** [comment]
Tested on v1.3.2 and WFM (got my debug message printed that file was ignored).
It wouldn't cause the message currently anyway as everything runs async.
