### ISSUE TITLE
don't consider the first column in a diff

### ISSUE THREAD

**Issue by glyph** [SublimeText/TrailingSpaces#9]
In a unified diff, the first column is always filled: either with a `+` to mean "added", a `-` to mean "removed", or a space to mean "nothing changed".  If a line is blank, this space will be there anyway.  It would be great for TrailingSpaces to _not_ highlight these, so that I can see legitimate trailing whitespace added by a diff without those distractions.

**Comment by rchl** [comment]
Diff scope is ignored in default settings currently.
