### ISSUE TITLE
Terminal pops up on Windows when saving

### ISSUE THREAD

**Issue by AndiDog** [SublimeText/TrailingSpaces#91]
Using default settings, a terminal pops up shortly after I save a file, and closes immediately. Quite unnerving.

**Comment by rchl** [comment]
Maybe that would be fixed by #92 although I don't see any explicit calls to subprocess.* that could trigger it. My thinking is that codecs.open() call could trigger console although it doesn't for me.

**Comment by rchl** [comment]
By fixed, I mean avoided, by not calling codecs.open() with default options.

**Comment by rchl** [comment]
Now I think it was probably some other package causing that behavior.
