### ISSUE TITLE
"trailing_spaces_syntax_ignore" doesn't work

### ISSUE THREAD

**Issue by Commenter123** [SublimeText/TrailingSpaces#96]
So I found this setting "trailing_spaces_syntax_ignore" which allows to "ignore" files.
Added this to the Plugin's user config:

`"trailing_spaces_syntax_ignore": ["Diff", "Markdown"]`
Then opened a .md file, Set Syntax to "Markdown", but the Plugin is still trimming trailing spaces.

What's the problem?
If I set "trailing_spaces_trim_on_save" to false, trailing spaces are not removed. So I think it's a problem of this plugin, isn't it?

**Comment by Aratramba** [comment]
I'm having the same problem with pug/jade-files. This package will remove spaces regardless of the syntax-ignore rule.

```json
"trailing_spaces_syntax_ignore": ["Pug", "Jade"]
```

**Comment by 3askaal** [comment]
Same for me.

**Comment by grelas** [comment]
Same for me, not able to ignore 'jade' files.

**Comment by jesusbv** [comment]
Me too, found [this](https://github.com/SublimeText/TrailingSpaces/issues/78#issuecomment-264223014), maybe help you in the meantime

**Comment by Tohsig** [comment]
Note for people like me that may still be having issues with this setting: **Restart ST**. As of this comment, changes to the TrailingSpaces settings don't seem to stick until you do. With that, using the base package name (e.g. "Markdown Extended") in the `"trailing_spaces_syntax_ignore"` array does indeed work. Sorry to bump an oldish thread, but this seems to be a common confusion.

**Comment by aleksey-khokhryakov** [comment]
In my case the base name of syntax file works: i'm using string "Bash" for syntax `Bourne Again Shell (bash)` with base file `Bash.sublime-syntax`.

**Comment by rchl** [comment]
ST restart is needed after changing settings currently.
